# Generated by Django 2.2.7 on 2019-11-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0003_auto_20191119_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boot',
            options={'verbose_name': 'Boot', 'verbose_name_plural': 'Boten'},
        ),
    ]
