# Generated by Django 2.2.7 on 2019-11-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='plaatsen',
            field=models.IntegerField(default=0),
        ),
    ]
