# Generated by Django 2.2.7 on 2019-11-21 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('plaatsen', models.IntegerField(default=0)),
                ('schipper', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Boot',
                'verbose_name_plural': 'Boten',
            },
        ),
        migrations.CreateModel(
            name='Geboekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Haven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaatsnaam', models.CharField(help_text='vul plaats van de haven in', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vistrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unieke ID voor deze trip', primary_key=True, serialize=False)),
                ('datum', models.DateField(blank=True, null=True)),
                ('boot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeetrips.Boot')),
                ('geboekt', models.ManyToManyField(to='zeetrips.Geboekt')),
            ],
            options={
                'ordering': ['datum'],
            },
        ),
        migrations.AddField(
            model_name='boot',
            name='haven',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeetrips.Haven'),
        ),
    ]
