# Generated by Django 2.2.7 on 2019-11-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zeetrips', '0002_auto_20191121_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vistrip',
            name='geboekt',
        ),
        migrations.AddField(
            model_name='vistrip',
            name='vissers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Geboekt',
        ),
    ]
