# Generated by Django 2.2.7 on 2019-11-21 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zeetrips', '0003_auto_20191121_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vistrip',
            name='vissers',
        ),
        migrations.AddField(
            model_name='vistrip',
            name='vissers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
