# Generated by Django 2.2.7 on 2019-11-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeetrips', '0005_auto_20191121_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boot',
            old_name='naam',
            new_name='naam_boot',
        ),
    ]
