# Generated by Django 2.2.7 on 2019-11-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeetrips', '0006_auto_20191122_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistrip',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
