# Generated by Django 2.2.7 on 2019-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeetrips', '0008_auto_20191122_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visplek',
            options={'verbose_name': 'Visplek', 'verbose_name_plural': 'Visplekken'},
        ),
        migrations.AddField(
            model_name='vistrip',
            name='soort_trip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
