# Generated by Django 2.2.7 on 2019-11-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeetrips', '0009_auto_20191122_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soort_trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort_trip', models.CharField(help_text='vul plaats van de haven in', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='vistrip',
            name='soort_trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeetrips.Soort_trip'),
        ),
    ]
