# Generated by Django 2.2.7 on 2019-11-25 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zeetrips', '0010_auto_20191122_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soort_trip',
            options={'verbose_name': 'Soort trip'},
        ),
        migrations.AlterField(
            model_name='soort_trip',
            name='soort_trip',
            field=models.CharField(help_text='vul soort trip in', max_length=200),
        ),
        migrations.AlterField(
            model_name='vistrip',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False),
        ),
    ]
