# Generated by Django 2.2.7 on 2019-11-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeetrips', '0012_auto_20191125_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistrip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
