# Generated by Django 2.2.7 on 2019-11-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeetrips', '0017_auto_20191125_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visplek',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
