# Generated by Django 2.2.8 on 2019-12-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeetrips', '0019_auto_20191126_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visplek',
            options={'permissions': (('can_addvisplek', '|Inschrijven voor visplek'),), 'verbose_name': 'Visplek', 'verbose_name_plural': 'Visplekken'},
        ),
    ]
