# Generated by Django 2.2.8 on 2020-01-06 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zeetrips', '0020_auto_20191231_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistrip',
            name='ingeschreven',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='visplek',
            unique_together={('vistrip', 'visser')},
        ),
    ]
