# Generated by Django 2.2.8 on 2020-01-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeetrips', '0021_auto_20200106_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vistrip',
            name='ingeschreven',
        ),
    ]
